### ISSUE TITLE
[Design] mock creation and sharing/validation

### ISSUE THREAD

**Issue by Al-Pragliola** [sighupio/fury-ui#11]
## Overview

Revise the old `cluster-detail` page to provide a layout that can scale with the type and amount of data we are expecting.

## Expected Outcome

Share and validate with stakeholders.

**Comment by AndreaDellaValle** [comment]
Figma link https://www.figma.com/file/SXaAn9aqzKpLjfp4y9A41p/fury-ui?type=design&node-id=0%3A1&t=IOz1qpG5KUftaxmd-1

**Comment by omissis** [comment]
LGTM, I would probably just be a little less aggressive with shadows, but it's a very minor detail.
