### ISSUE TITLE
Define contract between FE and BE using openapi

### ISSUE THREAD

**Issue by Al-Pragliola** [sighupio/fury-ui#2]
## Overview

As part of this issue, we need to establish a clear and standardized contract between the frontend (FE) and backend (BE) using OpenAPI. 

## Expected Outcome

An openapi.json file from which to generate frontend and backend types and data.

## Steps to be Taken

- [x] Define a contract and write the openapi.json file
- [x] Auto-generate structs and routes for backend

**Comment by AndreaDellaValle** [comment]
contract draft here: https://www.notion.so/Kickoff-6510516c895c4cf7869cd4cb080c24fb
